### ISSUE TITLE
Security question...

### ISSUE THREAD

**Issue by arturmamedov** [viddler/Examples#1]
Hi! I have some question about a viddler API.

I try use a cUrl upload and a cUrl request to uploadProgress for doing an drag and drop video upload directly. With this way my upload work perfectly, but a request to uploadProgress no (because in all proccess i receive a response with byte: 0, percent: 0, status: 1 ... and the last response are byte: ****, percent: 100, status: 2 ...) i suppose a dirrect cUrl upload don't work with uploadProgress.

I try your form upload with code from this repository, upload and progress work perfectly but i don't understood, is a good practice show in HTML form and in javascript a 'session_id' and 'token' i see this how a hole in security, no?

Sorry for bad english i hope someone understood and help me, good day :)

**Comment by mattfawcett** [comment]
Hi

As far as I know viddler.videos.uploadProgress should work regardless of how you upload the video. 

In terms of security, exposing the upload token in html/javascript is fine - it only allows a single file upload to your account. Exposing your session_id is not good practice because that session_id could then be used to gain access to your account.

**Comment by arturmamedov** [comment]
Allright, thank you very much. I try again :) with my preferite cUrl. I now realized that nobody show a 'session_id' but only 'endpoint' and 'token'. Good phping for all, bye :)
